name: "Review"
description: Review our tutorial
title: "[Review by]: "
labels: ["review", "feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give us feedback! We created this template to help prompt feedback. Feel free to follow it as much or as little as you like
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: tl;dr
      description: Your overall summary of the material
      placeholder: I thought this was...
      value: "I thought the tutorial was..."
    validations:
      required: true
  - type: dropdown
    id: experience
    attributes:
      label: Experience level
      description: How experienced do you consider yourself in Machine Learning?
      options:
        - Beginner
        - Intermediate
        - Expert
    validations:
      required: true
  - type: checkboxes
    id: sector
    attributes:
      label: What sector(s) do you align most closely with
      description: You may select more than one.
      options:
        - Libraries
        - Museums
        - University/Higher-education
        - Galleries
        - Archives
        - Other

